#server:
#  port: 8086
#  ssl:
#    key-store: classpath:tomcat.keystore
#    key-store-password: 123456
#    trust-store: classpath:tomcat.keystore
#    trust-store-password: 123456
#    BasicTest-auth: need

spring:
  application:
    name: web

  resources:
    static-locations: classpath:/static
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:mysql://182.61.48.200/telecom?useUnicode=true&characterEncoding=utf-8
    username: root
    password: qdc#@&oiwedadf##%WUIQ
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

